### ISSUE TITLE
Documentación sección técnicas y herramientas

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#10]
Indicar una visión general de la herramienta. Descripción funcional breve. Para qué se utiliza en la herramienta en el proyecto y referenciar a Web o libro.

**Comment by ers0026** [comment]
@bsc0001 falta una pequeña parte con la documentación.

**Comment by bsc0001** [comment]
Cierto! Me pongo a ello!

**Comment by ers0026** [comment]
@bsc0001 ahora si, todo esta correcto.
