### ISSUE TITLE
Manual de instalación de SonarQube

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#11]
Adjunto el anexo Manual de Usuario, en el que se explica cómo desplegar la instancia de SonarQube en local y en la plataforma OpenShift, cómo analizar un proyecto y la instalación de todas las herramientas utilizadas en los dos procesos anteriores.

**Comment by bsc0001** [comment]
@ers0026 Está bien el manual. Correcto.

**Comment by ers0026** [comment]
@bsc0001 pasamos la siguiente trabajo.
