### ISSUE TITLE
Crear anexo Manual del Administrador

### ISSUE THREAD

**Issue by bsc0001** [ers0026/GESPRO_Practicas#16]
Crear un manual del administrador con la parte de instalación y despliegue de la instancia de SonarQube, descrita en el manual de usuario. Incluir una descripción de las configuraciones realizadas.

**Comment by ers0026** [comment]
@bsc0001 te falta tener en cuenta el aspecto de la red. Te lo envio a proceso de nuevo.

**Comment by bsc0001** [comment]
@ers0026 Completado!
