### ISSUE TITLE
Escaneo del histórico de versiones de un TFG

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#17]
Creado el escaneo del histórico de versiones para los proyectos propuestos.

**Comment by bsc0001** [comment]
@ers0026 Parece que te has dejado la versión 1.1! Recuerda incluirla!

**Comment by ers0026** [comment]
@bsc0001 tienes razon, ahora mismo la añado y vuelves a revisar, esperemos que vaya todo bien.

**Comment by bsc0001** [comment]
@ers0026 Ahora lo veo todo perfecto!
