### ISSUE TITLE
Prueba desarrollo widget sonarQube

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#18]
Intentaremos resolver pequeños programas. Ej: Hola mundo

**Comment by bsc0001** [comment]
@ers0026 Tienes un bug en el widget

**Comment by ers0026** [comment]
@bsc0001 lo reviso, espero poder arreglarlo rápido.

**Comment by bsc0001** [comment]
Que rapido! Todo bien @ers0026
