### ISSUE TITLE
Incorporar nuevos proyectos en la instancia de SonarQube

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#20]
Incluir análisis de más trabajos fin de grado en la instancia de SonarQube.

**Comment by bsc0001** [comment]
@ers0026 Parece que te has dejado uno de los proyectos!

**Comment by ers0026** [comment]
@bsc0001 cierto es, menos mal que te diste cuenta, menudo fallo, lo incluyo ahora mismo.

**Comment by ers0026** [comment]
@bsc0001 ya esta arreglado. ¿Revisalo si puedes otra vez?

**Comment by bsc0001** [comment]
@ers0026 Si, ahora lo veo todo perfecto!
