### ISSUE TITLE
Widget de presentación para la instancia de SonarQube

### ISSUE THREAD

**Issue by bsc0001** [ers0026/GESPRO_Practicas#21]
Crear un widget que presente información acerca de la plataforma actual de evaluación de trabajos fin de grado.

**Comment by ers0026** [comment]
@bsc0001 veo correcto todo, pero se puede mejorar algun aspecto de la pagina 3.

**Comment by bsc0001** [comment]
Me pongo a ello! @ers0026

**Comment by bsc0001** [comment]
@ers0026 Revisado!

**Comment by ers0026** [comment]
@bsc0001 ahora si todo correcto
