### ISSUE TITLE
Apéndice B: Especificación de Requisitos

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#27]
Crear la documentación correspondiente al apéndice Especificación de Requisitos

**Comment by bsc0001** [comment]
@ers0026 Parece que nos están faltando algunos requisitos. ¿Puedes revisarlo tú?

**Comment by ers0026** [comment]
@bsc0001 ya esta todo comprobado revisarlo para dar tu correción

**Comment by bsc0001** [comment]
Todo bien! @ers0026
