### ISSUE TITLE
Aprendizaje del entorno de Bitbucket

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#3]
Necesidad de aprender las funcionalidades que ofrece Bitbucket para la gestión de un repositorio.
Se pretende realizar una gestión de las tareas llevadas a cabo durante la realización del proyecto mediante incidencias (issues), componentes (components) e hitos (milestones).

**Comment by bsc0001** [comment]
@ers0026 ten cuidado con los posibles fallos, a fijarse bien en todo.

**Comment by ers0026** [comment]
Estaré con los ojos bien abiertos @bsc0001
