### ISSUE TITLE
Despliegue de instancia local de SonarQube

### ISSUE THREAD

**Issue by ers0026** [ers0026/GESPRO_Practicas#4]
Despliegue de una instancia local de la herramienta SonarQube en la que se muestran los proyectos analizados. La instancia local es resultado de ejecutar una aplicación autónoma, sin necesidad de realizar ninguna instalación.

**Comment by bsc0001** [comment]
@ers0026 creo haber visto un fallo en la linea 30, revisalo a ver si es algún fallo grande.

**Comment by ers0026** [comment]
@bsc0001 reviso el programa, pero creo que esta bien realizado.
